### ISSUE TITLE
Prayer Time Library

### ISSUE THREAD

**Issue by rashnk** [ecmelkytz/ionic-prayer-time#1]
which prayertime Js library is used?

**Comment by ecmelkytz** [comment]
I haven't used any prayertime js library. I get prayer time data with http request from [Diyanet İşleri Başkanlığı](http://www.diyanet.gov.tr/)

**Comment by rashnk** [comment]
not all the places arelisted in place list, only major cities. good work anyway
Use the REST API for more accurate time for places https://aladhan.com/prayer-times-api

**Comment by ecmelkytz** [comment]
You're right. Thanks for sharing with me this api.

**Comment by rashnk** [comment]
welcome.
Join ionic developers chat group if interested.
https://chat.whatsapp.com/0bFNRotX4va21TgpR6L3dU

**Comment by rashnk** [comment]
https://github.com/rashnk/fw7Vue-IslamicPrayerTime
